dataset: dapt20

captures:  
  monday-pub: enp0s3-monday.pcap
  monday-pvt: enp0s3-monday-pvt.pcap
  tuesday-pub: enp0s3-public-tuesday.pcap
  tuesday-pvt: enp0s3-pvt-tuesday.pcap
  wednesday-pub: enp0s3-public-wednesday.pcap
  wednesday-pvt: enp0s3-pvt-wednesday.pcap
  thursday-pub: enp0s3-public-thursday.pcap
  thursday-pvt: enp0s3-pvt-thursday.pcap
  friday-pub: enp0s3-tcpdump-friday.pcap
  friday-pvt: enp0s3-tcpdump-pvt-friday.pcap

split:
  train: [monday-pub, monday-pvt, tuesday-pub, tuesday-pvt, wednesday-pub, wednesday-pvt]
  test:  [thursday-pub, thursday-pvt, friday-pub, friday-pvt]

stage_labels:
  - Reconnaissance
  - Establish Foothold
  - Lateral Movement
  - Data Exfiltration